services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      MONGO_URL: ${MONGO_URL}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      TZ: ${TZ}
    depends_on:
      - mongo
    networks:
      - app
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    networks:
      - app
      - proxy

networks:
  app:
    driver: bridge
  proxy:
    external: true
    name: proxy

volumes:
  mongo_data:
